package manual

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"act_gram/llm"
)

type RawLogEvent struct {
	Timestamp   int64  `json:"timestamp"`
	EventType   string `json:"type"` // "click", "input", "key_action"
	KeyName     string `json:"key,omitempty"`
	ClickX      int    `json:"x,omitempty"`
	ClickY      int    `json:"y,omitempty"`
	RelX        int    `json:"rel_x,omitempty"`
	RelY        int    `json:"rel_y,omitempty"`
	WindowTitle string `json:"window,omitempty"`
	Control     string `json:"control,omitempty"`
	ControlID   string `json:"control_id,omitempty"`
	Value       string `json:"value,omitempty"`
	ImageFile   string `json:"image_path,omitempty"`
}

type AutoGeneratedStep struct {
	StepNumber    int    `json:"step_number"`
	Title         string `json:"title"`
	Description   string `json:"description"`
	WindowTitle   string `json:"window_title"`
	TargetElement string `json:"target_element"`
	ActionType    string `json:"action_type"` // "click", "input", "shortcut"
	InputValue    string `json:"input_value"`
	UWSCode       string `json:"uws_code"`
	ImageFile     string `json:"image_file"`
	ClickX        int    `json:"click_x,omitempty"`
	ClickY        int    `json:"click_y,omitempty"`
	RelX          int    `json:"rel_x,omitempty"`
	RelY          int    `json:"rel_y,omitempty"`
}

type AutoSlicer struct{}

func NewAutoSlicer() *AutoSlicer {
	return &AutoSlicer{}
}

// SliceLogToScenario はフォルダ内の log.json をパースして、AIにより論理的ステップにセグメンテーションします
func (as *AutoSlicer) SliceLogToScenario(logDir string, ragContext string, provider llm.LLMProvider, model string) ([]ManualStep, error) {
	logFilePath := filepath.Join(logDir, "log.json")
	logData, err := os.ReadFile(logFilePath)
	if err != nil {
		return nil, fmt.Errorf("log.json の読み込みに失敗しました: %v", err)
	}

	var events []RawLogEvent
	if err := json.Unmarshal(logData, &events); err != nil {
		return nil, fmt.Errorf("生ログのパースに失敗しました: %v", err)
	}

	eventsJSON, _ := json.MarshalIndent(events, "", "  ")
	prompt := fmt.Sprintf(`
あなたは一流の業務システムコンサルタントおよびUWSCR自動化エンジニアです。
入力された時系列の操作履歴（クリック、テキスト入力、ショートカット、対象UI要素、アクティブウィンドウ情報）を分析し、**現場の作業者が読んですぐ理解できる業務手順書（マニュアル）**と**それを完全自動再現するUWSCRスクリプト**を作成してください。

【RAG業務ナレッジ】
%s

【操作履歴ログ】
"""
%s
"""

【ミッション】
一連の操作を、人間が理解しやすい3～8個の「業務機能ステップ」に分割（スライス）し、以下のJSON配列形式のみで出力してください：

[
  {
    "step_number": 1,
    "title": "ステップタイトル (例: 会計システムへのログイン)",
    "description": "操作者が迷わない明確な手順指示 (例: 1. ユーザーIDに『admin』を入力します。2. パスワードを入力し、『ログイン』ボタンをクリックします。)",
    "window_title": "対象のウィンドウ名または画面名",
    "target_element": "操作対象のUI要素名（例: ログインボタン、検索入力欄）",
    "action_type": "click または input または shortcut",
    "input_value": "入力したテキスト（入力操作の場合）",
    "uws_code": "このステップを単体で確実に再現できるUWSCRコード",
    "image_file": "このステップを最もよく表す画像ファイル名 (例: captures/event_12345.png)",
    "click_x": 主要な操作箇所のX座標 (数値),
    "click_y": 主要な操作箇所のY座標 (数値),
    "rel_x": ウィンドウ内相対X座標 (数値),
    "rel_y": ウィンドウ内相対Y座標 (数値)
  }
]

【UWSCR自動記述ルール（厳守）】
1. ウィンドウ操作: 必ず GETID で対象ウィンドウを取得し、ACW でアクティブ化してから操作してください。
   Dim id = GETID("ウィンドウタイトル")
   IFB id >= 0 THEN
       ACW(id)
       SLEEP(0.3)
   ENDIF
2. クリック操作:
   - ボタン名や要素名が判明している場合は clkitem(id, "ボタン名", CLK_BTN or CLK_UIA) を優先。
   - 座標クリックを行う場合は、必ず mouseorg(id) を使ってウィンドウ相対座標で実行し、終了後に mouseorg(0) で戻してください。
     mouseorg(id)
     btn(LEFT, CLICK, rel_x, rel_y, 200)
     mouseorg(0)
3. テキスト入力操作:
   - 入力対象欄にフォーカスを当てた後、SENDSTR(id, "入力文字列") または KBD で入力してください。
4. 適切な待機: ウィンドウ遷移や処理待ちには SLEEP(0.5) などを挟んで安定動作させてください。

出力フォーマットはマークダウン記号（` + "```" + `json 等）を含めず、純粋なJSON配列文字列のみを返却してください。
`, ragContext, string(eventsJSON))

	resp := provider.GenerateText(prompt, "", model)
	if resp.Error != nil {
		return nil, resp.Error
	}

	cleanJSON := cleanJSONResponse(resp.Text)
	var genSteps []AutoGeneratedStep
	if err := json.Unmarshal([]byte(cleanJSON), &genSteps); err != nil {
		return nil, fmt.Errorf("AIレスポンスのパースに失敗しました: %v. Raw: %s", err, resp.Text)
	}

	var manualSteps []ManualStep
	for _, gs := range genSteps {
		imgPath := ""
		if gs.ImageFile != "" {
			p := filepath.Join(logDir, gs.ImageFile)
			if _, err := os.Stat(p); err == nil {
				imgPath = p
			} else {
				p2 := filepath.Join(logDir, "captures", filepath.Base(gs.ImageFile))
				if _, err := os.Stat(p2); err == nil {
					imgPath = p2
				} else {
					imgPath = p
				}
			}
		}

		desc := gs.Description
		if desc == "" {
			desc = gs.Title
		}

		manualSteps = append(manualSteps, ManualStep{
			StepID:        gs.StepNumber,
			StepNumber:    gs.StepNumber,
			Title:         gs.Title,
			Instruction:   desc,
			Description:   desc,
			WindowTitle:   gs.WindowTitle,
			TargetElement: gs.TargetElement,
			ActionType:    gs.ActionType,
			InputValue:    gs.InputValue,
			UWSCode:       gs.UWSCode,
			ImagePath:     imgPath,
			ClickX:        gs.ClickX,
			ClickY:        gs.ClickY,
			RelX:          gs.RelX,
			RelY:          gs.RelY,
		})
	}

	return manualSteps, nil
}

func cleanJSONResponse(text string) string {
	text = strings.TrimSpace(text)
	if strings.HasPrefix(text, "```") {
		lines := strings.Split(text, "\n")
		if len(lines) > 2 {
			startIdx := 1
			if strings.HasPrefix(lines[0], "```json") || strings.HasPrefix(lines[0], "```") {
				startIdx = 1
			}
			endIdx := len(lines) - 1
			if strings.HasPrefix(lines[len(lines)-1], "```") {
				endIdx = len(lines) - 1
			}
			if endIdx > startIdx {
				text = strings.Join(lines[startIdx:endIdx], "\n")
			}
		}
	}
	return strings.TrimSpace(text)
}
