// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FetchModels(arg1) {
  return window['go']['main']['App']['FetchModels'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function HasAPIKey(arg1) {
  return window['go']['main']['App']['HasAPIKey'](arg1);
}

export function SaveAPIKey(arg1, arg2) {
  return window['go']['main']['App']['SaveAPIKey'](arg1, arg2);
}

export function SaveConfig(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveConfig'](arg1, arg2, arg3);
}
