// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function FetchModels(arg1:string):Promise<Array<string>>;

export function GetConfig():Promise<main.Config>;

export function HasAPIKey(arg1:string):Promise<boolean>;

export function RunScript(arg1:string):Promise<void>;

export function SaveAPIKey(arg1:string,arg2:string):Promise<void>;

export function SaveConfig(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SaveUWSCRPath(arg1:string):Promise<void>;
