// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CaptureSession():Promise<main.SessionContext>;

export function FetchModels(arg1:string):Promise<Array<string>>;

export function GenerateInteractiveManual(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function GenerateScript(arg1:string,arg2:string):Promise<string>;

export function GetConfig():Promise<main.Config>;

export function GetDefaultManualPath():Promise<string>;

export function GetDefaultScriptPath():Promise<string>;

export function HasAPIKey(arg1:string):Promise<boolean>;

export function RunScript(arg1:string):Promise<void>;

export function SaveAPIKey(arg1:string,arg2:string):Promise<void>;

export function SaveConfig(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SaveConfigs(arg1:string):Promise<void>;

export function SaveScriptFile(arg1:string,arg2:string):Promise<void>;

export function SaveUWSCRPath(arg1:string):Promise<void>;

export function SelectDirectory(arg1:string):Promise<string>;

export function SelectFile(arg1:string,arg2:string,arg3:string):Promise<string>;

export function SelectSaveFile(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;
