// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {manual} from '../models';

export function AskManualContext(arg1:string,arg2:string):Promise<string>;

export function CaptureSession():Promise<main.SessionContext>;

export function CheckAIConnection():Promise<boolean>;

export function CorrectScript(arg1:string,arg2:string,arg3:string):Promise<string>;

export function DrawMarker(arg1:string,arg2:number,arg3:number):Promise<string>;

export function ExecuteStep(arg1:number):Promise<manual.ManualStep>;

export function FetchModels(arg1:string):Promise<Array<string>>;

export function GenerateInteractiveManual(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function GenerateScenarioFromLog(arg1:string):Promise<Array<manual.ManualStep>>;

export function GenerateScript(arg1:string,arg2:string):Promise<string>;

export function GetConfig():Promise<main.Config>;

export function GetDefaultManualPath():Promise<string>;

export function GetDefaultScriptPath():Promise<string>;

export function GetImageBase64(arg1:string):Promise<string>;

export function GetLocalLLMConfig():Promise<main.LocalLLMConfig>;

export function HasAPIKey(arg1:string):Promise<boolean>;

export function MinimizeWindow():Promise<void>;

export function OpenKnowledgeDir():Promise<void>;

export function ProposeOptimization(arg1:string,arg2:string):Promise<string>;

export function ReadScriptFile(arg1:string):Promise<string>;

export function RestoreDefaultReference():Promise<void>;

export function RestoreWindow():Promise<void>;

export function RunInteractiveGuide():Promise<void>;

export function RunScript(arg1:string):Promise<void>;

export function SaveAPIKey(arg1:string,arg2:string):Promise<void>;

export function SaveConfig(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SaveConfigs(arg1:string):Promise<void>;

export function SaveCustomBaseURL(arg1:string):Promise<void>;

export function SaveErrorReflection(arg1:string,arg2:string):Promise<void>;

export function SaveKnowledgeDirAndURL(arg1:string,arg2:string):Promise<void>;

export function SaveLocalLLMConfig(arg1:string,arg2:string):Promise<void>;

export function SaveScriptFile(arg1:string,arg2:string):Promise<void>;

export function SaveUWSCRPath(arg1:string):Promise<void>;

export function SelectDirectory(arg1:string):Promise<string>;

export function SelectFile(arg1:string,arg2:string,arg3:string):Promise<string>;

export function SelectSaveFile(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function SetMiniMode(arg1:boolean,arg2:string):Promise<void>;

export function StartRecording():Promise<void>;

export function StopRecording():Promise<string>;

export function StopScript():Promise<void>;

export function SyncUWSCRReference():Promise<void>;

export function TestAPIKeyConnection(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function TestRunScript(arg1:string):Promise<main.TestRunResult>;
