// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CaptureSession() {
  return window['go']['main']['App']['CaptureSession']();
}

export function FetchModels(arg1) {
  return window['go']['main']['App']['FetchModels'](arg1);
}

export function GenerateInteractiveManual(arg1, arg2, arg3) {
  return window['go']['main']['App']['GenerateInteractiveManual'](arg1, arg2, arg3);
}

export function GenerateScript(arg1, arg2) {
  return window['go']['main']['App']['GenerateScript'](arg1, arg2);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetDefaultManualPath() {
  return window['go']['main']['App']['GetDefaultManualPath']();
}

export function GetDefaultScriptPath() {
  return window['go']['main']['App']['GetDefaultScriptPath']();
}

export function HasAPIKey(arg1) {
  return window['go']['main']['App']['HasAPIKey'](arg1);
}

export function RunScript(arg1) {
  return window['go']['main']['App']['RunScript'](arg1);
}

export function SaveAPIKey(arg1, arg2) {
  return window['go']['main']['App']['SaveAPIKey'](arg1, arg2);
}

export function SaveConfig(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveConfig'](arg1, arg2, arg3);
}

export function SaveConfigs(arg1) {
  return window['go']['main']['App']['SaveConfigs'](arg1);
}

export function SaveScriptFile(arg1, arg2) {
  return window['go']['main']['App']['SaveScriptFile'](arg1, arg2);
}

export function SaveUWSCRPath(arg1) {
  return window['go']['main']['App']['SaveUWSCRPath'](arg1);
}

export function SelectDirectory(arg1) {
  return window['go']['main']['App']['SelectDirectory'](arg1);
}

export function SelectFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['SelectFile'](arg1, arg2, arg3);
}

export function SelectSaveFile(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SelectSaveFile'](arg1, arg2, arg3, arg4);
}
